/*
 * generated by Xtext 2.10.0
 */
package org.example.domainmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends DelegatingScopeProvider {
}
